name: LogiStream Solutions

on:
  push:
    branches: [ "dev_matheus" ]
  pull_request:
    branches: [ "main" ]
    types: [closed]

  workflow_dispatch:
    inputs:
      action:
        type: choice
        description: '⚙️ Choose Terraform action'
        options:
          - deploy
          - destroy
        default: deploy

jobs:

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
#                               Environmental Development                                           #
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
  code-test:
    name: 🐍 Code Python Test
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    container: python:3.11-bullseye
    steps:
      - name: 🕵🏾 Checkout code
        uses: actions/checkout@v7

      - name: 👨🏾‍🔧 Install dependencies
        run: |
          apt-get update
          apt-get install -y build-essential make

      - name: 🐍 Setup Python and Install Python dependencies
        run: |
          python3 -m venv /opt/venv
          /opt/venv/bin/pip install --upgrade pip
          /opt/venv/bin/pip install -r ./modules/requirements-dev.txt
          echo "/opt/venv/bin" >> $GITHUB_PATH

      - name: 🧪 Run tests
        run: |
          echo "Running tests 👀"
          make coverage

  tf-test:
    name: ⚙️ Terraform Test
    runs-on: ubuntu-latest
    needs: code-test
    if: github.ref != 'refs/heads/main'
    container:
      image: ${{ vars.TF_DEPLOY_IMAGE }}
      options: --platform=linux/amd64
    steps:
      - name: 🕵🏾 Checkout code
        uses: actions/checkout@v7

      - name: 🧑🏾‍✈️ Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
          project_id: ${{ vars.GCP_PROJECT_ID}}

      - name: 🕵🏾 validate Terraform configuration
        run: |
          cd ./configs/terraform
          echo '🚧 Creating credentials file... 🚧'
          echo '${{ secrets.TERRAFORM_TFVARS }}' > terraform.tfvars
          terraform init
          terraform workspace select dev || terraform workspace new dev
          terraform validate
          terraform test
          echo "Whole Terraform configuration is valid ✅"

      - name: 💁🏾‍♂️ Clean up
        run: rm -f ./configs/terraform/*.json


# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
#                             Environmental Development / Production                                #
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
  tf-deploy:
    name: ⚙️ Terraform Deploy
    runs-on: ubuntu-latest
    needs: tf-test
    if: github.event.inputs.action == 'deploy'
    container:
      image: ${{ vars.TF_DEPLOY_IMAGE }}
      options: --platform=linux/amd64
    steps:
      - name: 🕵🏾 Checkout code
        uses: actions/checkout@v7

      - name: 🧑🏾‍✈️ Authenticate to GCP
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
          project_id: ${{ vars.GCP_PROJECT_ID }}

      - name: 🐍 Setup Python and Install Python dependencies
        run: |
            python3 -m venv /opt/venv
            . /opt/venv/bin/activate
            pip install --upgrade pip
            pip install -r ./src/requirements.txt

      - name: Terraform Deploy
        run: |
            . /opt/venv/bin/activate
            cd ./configs/terraform
            echo '🚧 Creating credentials file... 🚧'
            echo '${{ secrets.TERRAFORM_TFVARS }}' > terraform.tfvars
            terraform init
            terraform workspace select dev || terraform workspace new dev
            terraform apply -auto-approve
            echo "Whole Terraform configuration is applied successfully ✅"

      - name: 💁🏾‍♂️ Clean up
        run: rm -f ./configs/terraform/*.json


  tf-destroy:
    name: 🔨 Terraform Destroy
    runs-on: ubuntu-latest
    if: github.event.inputs.action == 'destroy'
    container:
      image: ${{ vars.TF_DEPLOY_IMAGE }}
      options: --platform=linux/amd64
    steps:
      - name: 🕵🏾 Checkout code
        uses: actions/checkout@v7

      - name: 🧑🏾‍✈️ Authenticate to GCP
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
          project_id: ${{ vars.GCP_PROJECT_ID }}

      - name: Terraform Destroy
        run: |
          cd ./configs/terraform
          echo '🚧 Creating tfvars file... 🚧'
          echo '${{ secrets.TERRAFORM_TFVARS }}' > terraform.tfvars
          terraform init
          terraform workspace select dev || terraform workspace new dev
          terraform destroy -auto-approve
          echo "✅ Terraform resources destroyed"

      - name: 💁🏾‍♂️ Clean up
        run: rm -f ./configs/terraform/*.json